apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: movies-service-circuit-breaker
  namespace: cinemaabyss
spec:
  host: movies-service.cinemaabyss.svc.cluster.local
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 15
      http:
        http1MaxPendingRequests: 15
        maxRequestsPerConnection: 15